# FILE READ & WRITE WITH ERROR HANDLING

DEF MODIFY_CONTENT(CONTENT):
    """EXAMPLE MODIFICATION: CONVERT TEXT TO UPPERCASE"""
    RETURN CONTENT.UPPER()

# ASK THE USER FOR THE FILENAME
FILENAME = INPUT("ENTER THE NAME OF THE FILE TO READ: ")

TRY:
    # TRY OPENING AND READING THE FILE
    WITH OPEN(FILENAME, "R") AS FILE:
        CONTENT = FILE.READ()

    # MODIFY THE CONTENT
    MODIFIED_CONTENT = MODIFY_CONTENT(CONTENT)

    # WRITE TO A NEW FILE
    NEW_FILENAME = "MODIFIED_" + FILENAME
    WITH OPEN(NEW_FILENAME, "W") AS NEW_FILE:
        NEW_FILE.WRITE(MODIFIED_CONTENT)

    PRINT(F"FILE SUCCESSFULLY MODIFIED AND SAVED AS '{NEW_FILENAME}'.")

EXCEPT FILENOTFOUNDERROR:
    PRINT("ERROR: THE FILE DOES NOT EXIST. PLEASE CHECK THE FILENAME AND TRY AGAIN.")

EXCEPT PERMISSIONERROR:
    PRINT("ERROR: YOU DON�T HAVE PERMISSION TO READ THIS FILE.")

EXCEPT EXCEPTION AS E:
    PRINT(F"AN UNEXPECTED ERROR OCCURRED: {E}")